layout: sidebar
style: light

repository: BudgetArms/BudgetArms.github.io

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    unpinned: true
    archived: false
    forks: true
    projects:
    # - repo-name


# extra:
social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://explore-feed.github.com/topics/cpp/cpp.png
  - name: Gameplay Programming

  - name: Vulkan
    web_url: https://www.vulkan.org/
    image_url: https://www.vulkan.org/user/themes/vulkan/images/logo/vulkan-logo.svg

  - name: Gameplay Programming

skills:
  - name: C++
    web_url: https://github.com/topics/cpp
    image_url: https://explore-feed.github.com/topics/cpp/cpp.png

  - name: C#
    web_url: https://github.com/topics/csharp
    image_url: https://explore-feed.github.com/topics/csharp/csharp.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript/
    image_url: https://explore-feed.github.com/topics/javascript/javascript.png

  - name: CMake
    web_url: https://cmake.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/1/13/Cmake.svg

  - name: Arduino
    web_url: https://github.com/topics/arduino
    image_url: https://explore-feed.github.com/topics/arduino/arduino.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://explore-feed.github.com/topics/git/git.png

  - name: Perforce
    web_url: https://www.perforce.com/products/helix-core-apps/helix-visual-client-p4v
    image_url: https://www.perforce.com/themes/custom/p4base/assets/images/logo.svg

  - name: Unreal Engine 5
    web_url: https://github.com/topics/unreal-engine
    image_url: https://explore-feed.github.com/topics/unreal-engine/unreal-engine.png

  - name: Unity
    web_url: https://github.com/topics/unity
    image_url: https://explore-feed.github.com/topics/unity/unity.png

  - name: WebAssembly
    web_url: https://github.com/topics/wasm
    image_url: https://explore-feed.github.com/topics/web-assembly/web-assembly.png

  - name: Rider
    web_url: https://www.jetbrains.com/rider/
    image_url: https://www.jetbrains.com/guide/assets/logo-135a4cec.png

  - name: Visual Studio
    web_url: https://github.com/topics/visual-studio
    image_url: https://explore-feed.github.com/topics/visual-studio/visual-studio.png

  - name: Visual Studio Code
    web_url: https://github.com/topics/visual-studio-code
    image_url: https://explore-feed.github.com/topics/visual-studio-code/visual-studio-code.png



